//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalSigns
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMO
    {
        public int hmoid { get; set; }
        public string hmoname { get; set; }
        public string hmoaddress { get; set; }
        public Nullable<int> stateid { get; set; }
        public string hmocountry { get; set; }
        public string hmocontact { get; set; }
        public string hmophone1 { get; set; }
        public string hmophone2 { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string email { get; set; }
        public Nullable<int> typeid { get; set; }
        public string hmonumber { get; set; }
    
        public virtual State State { get; set; }
    }
}
