//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalSigns
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.VitalSigns = new HashSet<VitalSign>();
        }
    
        public string patientid { get; set; }
        public Nullable<int> staffid { get; set; }
        public string title { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string middlename { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string securityid { get; set; }
        public string securitynumber { get; set; }
        public string maritalstatus { get; set; }
        public string address { get; set; }
        public Nullable<int> stateid { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string postalcode { get; set; }
        public string mothername { get; set; }
        public string guardianname { get; set; }
        public string emergencycontact { get; set; }
        public string emergencyphone { get; set; }
        public string homephone { get; set; }
        public string workphone { get; set; }
        public string mobilephone { get; set; }
        public string email { get; set; }
        public string occupation { get; set; }
        public string photopath { get; set; }
        public string employername { get; set; }
        public string employeraddress { get; set; }
        public string employercity { get; set; }
        public Nullable<int> employerstateid { get; set; }
        public string employercountry { get; set; }
        public Nullable<System.DateTime> dateofdeath { get; set; }
        public string deathcause { get; set; }
        public string hmono1 { get; set; }
        public string hmoname1 { get; set; }
        public string hmono2 { get; set; }
        public string hmoname2 { get; set; }
        public string hmono3 { get; set; }
        public string hmoname3 { get; set; }
        public string principalcode { get; set; }
        public string relationship { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<bool> inactive { get; set; }
        public Nullable<int> cardtypeid { get; set; }
        public Nullable<System.DateTime> datedeactivated { get; set; }
        public string genotype { get; set; }
        public string bloodgroup { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public int autoid { get; set; }
        public string servicetype { get; set; }
        public string plantype { get; set; }
    
        public virtual enrollee_type enrollee_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitalSign> VitalSigns { get; set; }
        public virtual State State { get; set; }
    }
}
