//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalSigns
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.VitalSigns = new HashSet<VitalSign>();
        }
    
        public int staffid { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public Nullable<int> titleid { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string mobilephone { get; set; }
        public string homephone { get; set; }
        public string workphone { get; set; }
        public string emergencycontact { get; set; }
        public string emergencyphone { get; set; }
        public Nullable<int> designationid { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> ProviderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitalSign> VitalSigns { get; set; }
    }
}
