//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalSigns
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSign
    {
        public int vitalid { get; set; }
        public string patientid { get; set; }
        public Nullable<int> staffid { get; set; }
        public string temperature { get; set; }
        public string pulse { get; set; }
        public string weight { get; set; }
        public string bloodpressure { get; set; }
        public string height { get; set; }
        public string respiration { get; set; }
        public string comments { get; set; }
        public Nullable<bool> isfileattached { get; set; }
        public string docname { get; set; }
        public string docpath { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string BMI { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
